# Generated by Django 4.2.1 on 2023-05-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRManagementSystemApp', '0002_remove_company_employees_remove_department_employees_and_more'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE Department, Company, CustomUser, Request;", reverse_sql=migrations.RunSQL.noop),
    ]
