# Generated by Django 4.1.4 on 2023-05-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRManagementSystemApp', '0002_remove_company_employees_remove_department_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined')], default='accepted', max_length=10),
        ),
    ]
